config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chat_messages
  resources :products
  resources :histories
  resources :bookings
  resources :manage_bookings
  resources :profile
  resources :bills, only: [:index, :show, :update]
  resources :users do
    collection do
      post :import
    end
  end
  get :update_password, to: "welcome#update_password", as: :update_password
  put :edit_password, to: "welcome#edit_password", as: :edit_password
  resources :rooms do
    collection do
      post :import
    end
  end
  resources :carts do
    collection do
      patch :update_quantity
      post :checkout_momo
      get :checkout
      put :cash
    end
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root "welcome#index"
  get "shop", to: "welcome#shop"
  get "shop_detail/:id", to: "welcome#shop_detail", as: :shop_detail
  get "spa", to: "welcome#spa", as: :spa
  namespace :api do
    namespace :v1 do
      resources :bills, only: [:create]
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ActiveStorage::SetCurrent

  def index
    if current_user && can?(:manage, Bill)
      redirect_to current_user.has_role?(:admin) ? users_path : products_path
    else
      @cart = current_user ? current_user.carts.active.count : 0
    end
  end

  def shop
    q = params[:category]
    qq = params[:q]
    @products = q ? Product.where(category: q) : Product.all
    @products = qq ? @products.where("products.name like ? or products.category like ?", "%#{qq}%", "%#{Product.categories[qq] || Product.categories.values}%") : @products
    @products = @products.page(params[:page] || 1).per(@limit).order(created_at: :desc)
  end

  def shop_detail
    @product = Product.find_by id: params[:id]
  end

  def spa

  end


  def update_password
  end

  def edit_password
    @user = current_user
    if @user.update params.require(:user).permit(:password, :password_confirmation)
      flash[:notice] = "Change password successfully!"
    else
      flash[:notice] = @user.errors.full_messages.to_sentence
    end
    redirect_to shop_path
  end
end

app/views/welcome/_product.html.erb
<div class="col-lg-4 col-md-4 col-sm-6" id="<%= "product_#{product.id}" %>">
  <div class="collection-card">
    <div class="offer-card">
      <span>Offer</span>
    </div>
    <div class="collection-img">
      <img class="img-gluid" src="<%= product.image_url %>" alt="" style="height: 168px;object-fit: contain;">
      <%
=begin%>
 <div class="view-dt-btn">
        <div class="plus-icon">
          <i class="bi bi-plus"></i>
        </div>
        <a href="#">View Details</a>
      </div> 
<%
=end%>
      <ul class="cart-icon-list">
        <li>
          <%= form_for Cart.new, url: carts_path, data: { turbo: true }, html: {id: "add_to_cart_#{product.id}"}, method: :post do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.hidden_field :user_id, value: current_user&.id %>
            <button type="submit"><a><%= image_tag "icon/Icon-cart3.svg" %></a></button>
          <% end %>
<!--          <a href="cart.html">-->
          <%#= image_tag "icon/Icon-cart3.svg" %>
<!--          </a>-->
        </li>
        <%
=begin%>
 <li><a href="#"><%= image_tag "icon/Icon-favorites3.svg" %></a></li> 
<%
=end%>
      </ul>
    </div>
    <div class="collection-content text-center">
      <h4><a href="<%= shop_detail_path(product.id) %>"><%= product.name %></a></h4>
      <div class="price">
        <h6><%= number_to_currency(product.price,
          unit: "VND", format: "%n %u", precision: 0) %></h6>
      </div>
      <%
=begin%>
 <div class="review">
        <ul>
          <li><i class="bi bi-star-fill"></i></li>
          <li><i class="bi bi-star-fill"></i></li>
          <li><i class="bi bi-star-fill"></i></li>
          <li><i class="bi bi-star-fill"></i></li>
          <li><i class="bi bi-star-fill"></i></li>
        </ul>
        <span>(50)</span>
      </div> 
<%
=end%>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% unless current_user && current_user.has_role?(:admin) %>
  <!-- ========== Hero Style3 Start============= -->
  <div class="hero3 mb-90">
    <div class="background-text">
      <h2 class="marquee_text">
        <%= image_tag "icon/marque-foot.svg" %>
        <span>Get exciting Discount</span> Up To 50%
        <%= image_tag "icon/marque-foot.svg" %><span>On Your first buying</span> Up To 50%</h2>
    </div>
    <div class="swiper hero3-slider">
      <div class="swiper-wrapper">
        <% Product.limit(3).each do |product| %>
          <div class="swiper-slide">
            <div class="hero-wrapper">
              <div class="container">
                <div class="row align-items-center">
                  <div class="col-lg-6">
                    <div class="banner-content">
                      <h6>Limited Offer</h6>
                      <h1><%= product.name %></h1>
                      <div class="btn-group">
                        <a class="primary-btn5 btn-md" href="<%= shop_path %>">Shop Now</a>
                        <a class="primary-btn6" href="<%= shop_detail_path(product.id) %>">View Details</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-6 d-flex justify-content-end">
                    <div class="hero-img">
                      
                      <%= image_tag product.image_url %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="right-sidebar">
      <div class="slider-pagination-area">
        <div class="h3-hero-slider-pagination"></div>
      </div>
    </div>
  </div>
  <!-- ========== Hero Style3 Start============= -->
  <!-- ========== Home3 Categories Start============= -->
  <div class="home3-categoty-area pt-120 mb-120">
    <div class="container">
      <div class="row mb-60">
        <div class="col-lg-12 d-flex align-items-center justify-content-between flex-wrap gap-3">
          <div class="section-title3">
            <h2><%= image_tag "icon/h3-sec-tt-vect-left.svg" %><span>Browse By Categories</span><%= image_tag "icon/h3-sec-tt-vect-right.svg" %></h2>
          </div>
          <div class="slider-btn-wrap">
            <div class="slider-btn prev-btn-11">
              <i class="bi bi-arrow-left"></i>
            </div>
            <div class="slider-btn next-btn-11">
              <i class="bi bi-arrow-right"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 d-flex justify-content-center">
          <div class="swiper h3-category-slider">
            <div class="swiper-wrapper">
              <% Product.categories.each do |ca| %>
              <div class="swiper-slide">
                <div class="category-card">
                  <a href="shop.html" class="category-card-inner">

                    <div class="category-card-front">
                      <div class="category-icon">
                        <%= image_tag "icon/#{ca[0] == "small_animal" ? "Rabbit" : ca[0]}.svg" %>
                      </div>
                      <div class="content">
                        <h4><%= ca[0].humanize %> Supplies</h4>
                      </div>
                    </div>
                    <div class="category-card-back">
                      <%= image_tag "bg/h3-category-1.png" %>
                    </div>
                  </a>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ========== Home3 Categories End============= -->

  <!-- ========== Home3 Colection Start============= -->
  <div class="home3-collection-area mb-120">
    <div class="container">
      <div class="row mb-60">
        <div class="col-lg-12 d-flex align-items-center justify-content-between flex-wrap gap-3">
          <div class="section-title3">
            <h2><%= image_tag "icon/h3-sec-tt-vect-left.svg" %><span>Find Pet Collections</span><%= image_tag "icon/h3-sec-tt-vect-right.svg" %></h2>
          </div>
          <div class="h3-view-btn d-md-flex d-none">
            <a href="shop.html">View All Product<%= image_tag "icon/haf-button-2.svg" %></a>
          </div>
        </div>
      </div>
      <div class="row g-4 justify-content-center">
        <% Product.limit(3).each do |product| %>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="collection-card">
            <div class="offer-card sale">
              <span>Hot Sale</span>
            </div>
            <div class="collection-img">
              <%= image_tag product.image_url, style: "height: 168px;object-fit: contain;" %>
              <div class="view-dt-btn">
                <div class="plus-icon">
                  <i class="bi bi-plus"></i>
                </div>
                <a href="<%= shop_detail_path(product.id)%>">View Details</a>
              </div>
              <ul class="cart-icon-list">
                <%= form_for Cart.new, url: carts_path, data: { turbo: true }, html: {id: "add_to_cart_#{product.id}"}, method: :post do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.hidden_field :user_id, value: current_user&.id %>
            <button type="submit"><a><%= image_tag "icon/Icon-cart3.svg" %></a></button>
          <% end %>
              </ul>
            </div>
            <div class="collection-content text-center">
              <h4><a href="<%= shop_detail_path(product.id)%>"><%= product.name%></a></h4>
              <div class="price">
                <h6><%= number_to_currency(product.price,
                  unit: "VND", format: "%n %u", precision: 0) %></h6>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="row d-md-none d-block pt-30">
        <div class="col-lg-12 d-flex justify-content-center">
          <div class="h3-view-btn">
            <a href="<%= shop_path %>">View All Product<%= image_tag "icon/haf-button-2.svg" %></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ========== Home3 Blog End============= -->
<% end %>

app/views/welcome/shop.html.erb
<div class="shop-page pt-120 mb-120">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="shop-sidebar">
          <form enctype="multipart/form-data" action="/shop" accept-charset="UTF-8" method="get">
<!--            <div class="shop-widget">-->
<!--              <h5 class="shop-widget-title">Price Range</h5>-->
<!--              <div class="range-widget">-->
<!--                <div id="slider-range" class="price-filter-range" style="height: unset !important;"></div>-->
<!--                <div class="mt-25 d-flex justify-content-between gap-4">-->
<!--                  <input type="number" name="min_price" disabled min=0 max="1000000" id="min_price" class="price-range-field block shadow rounded-md border border-gray-200 outline-none price-range" style="color: #F46F30" />-->
<!--                  <input type="number" name="max_price" disabled min=0 max="1000000" id="max_price" class="price-range-field block shadow rounded-md border border-gray-200 outline-none price-range" style="color: #F46F30" />-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
            <div class="shop-widget">
              <div class="check-box-item">
                <h5 class="shop-widget-title">Category</h5>
                <div class="checkbox-container">
                  <label class="containerss">Dog
                    <input type="checkbox" name="category[]" value="dog" <%= params[:category] && params[:category].include?("dog") ? "checked" : '' %>>
                    <span class="checkmark"></span>
                  </label>
                  <label class="containerss">Cat
                    <input type="checkbox" name="category[]" value="cat" <%= params[:category] && params[:category].include?("cat") ? "checked" : '' %>>
                    <span class="checkmark"></span>
                  </label>
                  <label class="containerss">Bird
                    <input type="checkbox" name="category[]" value="bird" <%= params[:category] && params[:category].include?("bird") ? "checked" : '' %>>
                    <span class="checkmark"></span>
                  </label>
                  <label class="containerss">Fish
                    <input type="checkbox" name="category[]" value="fish" <%= params[:category] && params[:category].include?("fish") ? "checked" : '' %>>
                    <span class="checkmark"></span>
                  </label>
                  <label class="containerss">Small Animal
                    <input type="checkbox" name="category[]" value="small_animal" <%= params[:category] && params[:category].include?("small_animal") ? "checked" : '' %>>
                    <span class="checkmark"></span>
                  </label>
                </div>
              </div>
            </div>
            <button class="primary-btn3 btn-lg" type="submit">Search</button>
          </form>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="row mb-50">
          <div class="col-lg-12">
            <div class="multiselect-bar">
              <h6>shop</h6>
              <div class="multiselect-area">
                <div class="single-select">
                  <span>Show</span>
                  <%= form_tag('/shop', remote: true, id: 'limit_form', method: :get, class: "d-flex flex-row justify-content-end") do %>
                    <%= select_tag :limit, options_for_select([12, 25, 50, 100], selected: params[:limit] || 12), onchange: "$('#limit_form').submit();", class: "defult-select-drowpown" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row g-4 justify-content-center">
          <% @products.each do |product| %>
          <%= render partial: "welcome/product", locals: {product: product} %>
            <% end %>
        </div>
        <div class="row pt-70">
          <div class="col-lg-12 d-flex justify-content-center">
            <div class="paginations-area">
              <nav aria-label="Page navigation example">
                <%= paginate @products %>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
    // $("input[data-type='currency']").on({
    //     change: function(event) {
    //         if(event.which >= 37 && event.which <= 40) return;
    //
    //         console.log(1)
    //         // format number
    //         $(this).val(function(index, value) {
    //             return value
    //                 .replace(/\D/g, "")
    //                 .replace(/\B(?=(\d{3})+(?!\d))/g, ".")
    //                 ;
    //         });
    //     },
    // });
    $(document).ready(function() {
        $("#slider-range").slider({
            values: [20000, 30000]
        });
    });
</script>

app/views/welcome/shop_detail.html.erb
<div class="shop-details-page pt-120 mb-120">
  <div class="container">
    <div class="row g-lg-4 gy-5 mb-120">
      <div class="col-lg-7">
        <div class="tab-content tab-content1" id="v-pills-tabContent">
          <div
            class="tab-pane fade active show"
            id="v-pills-img1"
            role="tabpanel"
            aria-labelledby="v-pills-img1-tab"
          >
            <img class="img-fluid" src="<%= @product.image_url %>" alt="" />
          </div>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="shop-details-content">
          <h3><%= @product.name %></h3>
          <div class="price-tag">
            <h4>
              <%= number_to_currency(@product.price, unit: "VND", format: "%n
              %u", precision: 0) %>
            </h4>
          </div>
          <div
            class="shop-quantity d-flex align-items-center justify-content-start mb-20"
          >
            <%= form_for Cart.new, url: carts_path, data: { turbo: true }, html: {id: "add_to_cart_#{@product.id}"}, method: :post do |f| %> 
            <%= f.hidden_field :product_id, value: @product.id %> 
            <%= f.hidden_field :user_id, value: current_user&.id %>
            <button type="submit">
              <a class="primary-btn3">Add to cart</a>
            </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-120">
      <div class="col-lg-12">
        <div
          class="nav nav2 nav nav-pills"
          id="v-pills-tab2"
          role="tablist"
          aria-orientation="vertical"
        >
          <button
            class="nav-link active"
            id="v-pills-home-tab"
            data-bs-toggle="pill"
            data-bs-target="#v-pills-home"
            type="button"
            role="tab"
            aria-controls="v-pills-home"
            aria-selected="false"
          >
            Description
          </button>
        </div>

        <div class="tab-content tab-content2" id="v-pills-tabContent2">
          <div
            class="tab-pane fade active show"
            id="v-pills-home"
            role="tabpanel"
            aria-labelledby="v-pills-home-tab"
          >
            <div class="description">
              <p class="para-2 mb-3">
                <%= @product.description %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/update_password.html.erb
<div class="signup-section pt-120 pb-120">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-xl-6 col-lg-8 col-md-10">
        <div class="form-wrapper wow fadeInUp" data-wow-duration="1.5s" data-wow-delay=".2s">
          <div class="form-title">
            <h3>Change your password</h3>
          </div>
          <%= form_for(current_user, url: edit_password_path, html: { method: :put }) do |f| %>
            <div class="row">
              <div class="col-md-12">
                <div class="form-inner">
                  <label>Password *</label>
                  <%= f.password_field :password, autocomplete: "new-password", placeholder: "Enter Your Password" %>
                  <i class="bi bi-eye-slash" id="togglePassword"></i>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-inner">
                  <label>Confirm Password *</label>
                  <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Confirm Password" %>
                  <i class="bi bi-eye-slash" id="togglePassword2"></i>
                </div>
              </div>
            </div>
            <button class="account-btn" type="submit">Change my password</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>