config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chat_messages
  resources :products
  resources :histories
  resources :bookings
  resources :manage_bookings
  resources :profile
  resources :bills, only: [:index, :show, :update]
  resources :users do
    collection do
      post :import
    end
  end
  get :update_password, to: "welcome#update_password", as: :update_password
  put :edit_password, to: "welcome#edit_password", as: :edit_password
  resources :rooms do
    collection do
      post :import
    end
  end
  resources :carts do
    collection do
      patch :update_quantity
      post :checkout_momo
      get :checkout
      put :cash
    end
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root "welcome#index"
  get "shop", to: "welcome#shop"
  get "shop_detail/:id", to: "welcome#shop_detail", as: :shop_detail
  get "spa", to: "welcome#spa", as: :spa
  namespace :api do
    namespace :v1 do
      resources :bills, only: [:create]
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  enum status: [:active, :inactive]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::RecordIdentifier
  include ActiveStorage::SetCurrent

  before_action :set_product, only: [:create, :update_quantity]
  before_action :total, only: [:index, :checkout_momo, :checkout, :cash]
  def index
    products = current_user.carts.active.group(:product_id).count.keys
    @carts = Product.where(id: products)
  end

  def create
    respond_to do |format|
      carts_active = current_user.carts.active.where(product_id: cart_params[:product_id]).count
      if carts_active >= @product.quantity
        format.html{redirect_to shop_path, notice: "You can't add more than #{@product.quantity} products to your cart."}
      elsif current_user.carts.create! cart_params
        @cart = current_user.carts.active.count
        format.turbo_stream
        format.html{redirect_to shop_path}
        # flash[:notice] = "Added a product to cart."
      else
        format.html
      end
    end
  end

  def update_quantity
    carts_active = current_user.carts.active.where(product_id: @product.id)
    message = ""
    if params[:quantity]&.to_i > @product.quantity
      redirect_to carts_path, notice: "You can't add more than #{@product.quantity} products to your cart."
    elsif params[:quantity]&.to_i > carts_active.count
      add_carts = params[:quantity]&.to_i - carts_active.count
      add_carts.times do
        current_user.carts.create! product_id: @product.id
      end
      @total = 0
    current_user.carts.active.includes(:product).each do |l_prod|
      @total += l_prod.product.price
    end
    @cart = current_user.carts.active.count
    respond_to do |format|
        format.turbo_stream
    end
    else
      remove_carts = carts_active.count - params[:quantity]&.to_i
      remove_carts.times do
        carts_active.first.destroy!
        carts_active.reload
      end
      @total = 0
    current_user.carts.active.includes(:product).each do |l_prod|
      @total += l_prod.product.price
    end
    @cart = current_user.carts.active.count
    respond_to do |format|
        format.turbo_stream
    end
    end
    
  end

  def checkout_momo
    momo = Momo::GetPaymentUrlService.call({user: current_user, amount: @total, carts: @carts, params: params})
    if momo["resultCode"] == 0
      redirect_to momo["payUrl"], allow_other_host: true
    else
      flash[:notice] = "Checkout momo fail!"
      redirect_to carts_path
    end
  end

  def checkout
    products = current_user.carts.active.group(:product_id).count.keys
    @products = Product.where(id: products)
  end

  def destroy
      carts = current_user.carts.active.where product_id: params[:id]
      carts.update_all status: :inactive
      flash[:notice] = "Remove cart successfully!"
      redirect_to carts_path
  end

  def cash
    random_token = SecureRandom.hex(10)
    carts = current_user.carts
    data_cart = carts.active.group(:product_id).count(:product_id)
    products = Product.where(id: data_cart.keys)
    bill = Bill.create order_id: "Cash_#{random_token}", amount: @total, order_info: current_user.email, status: :cash, user_id: current_user.id, 
      first_name: current_user.first_name, last_name: current_user.last_name, address: current_user.address, phone_number: current_user.phone_number
    products.each do |product|
      bill.bill_products.create product_id: product.id, name: product.name, quantity: data_cart[product.id], total_amount: product.price * data_cart[product.id]
    end
    current_user.carts.update_all status: :inactive
    flash[:notice] = "Payment in cash successfully!"
    redirect_to shop_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(cart_params[:product_id])
  end

  def total
    @carts = current_user.carts
    @total = 0
    current_user.carts.active.includes(:product).each do |l_prod|
      @total += l_prod.product.price
    end
  end

  # Only allow a list of trusted parameters through.
  def cart_params
    params.require(:cart).permit(:product_id, :user_id)
  end
end

app/views/carts/_cart.html.erb
<tr>
  <td data-label="Delete">
    <%= link_to cart_path(product.id), data: { turbo: true, turbo_method:
    :delete } do %>
    <div class="delete-icon">
      <i class="bi bi-x"></i>
    </div>
    <% end %>
  </td>
  <td data-label="Image">
    <%= image_tag product.image_url ? product.image_url : '' %>
  </td>
  <td data-label="Food Name">
    <a href="#"><%= product.name %></a>
  </td>
  <td data-label="Discount Price">
    <%= number_to_currency(product.price, unit: "VND", format: "%n %u",
    precision: 0) %>
  </td>
  <td data-label="Quantity">
    <div class="quantity d-flex align-items-center">
      <div class="quantity-nav nice-number d-flex align-items-center">
        <%= form_for Cart.new, url: update_quantity_carts_path, data: { turbo:
        true }, html: {id: "update_quantity_#{product.id}"}, method: :patch do
        |f| %> <%= f.hidden_field :product_id, value: product.id %>
        <input
          type="number"
          value="<%= current_user.carts.active.where(product_id: product.id).count %>"
          min="1"
          name="quantity"
        />
        <% end %>
      </div>
    </div>
  </td>
  <td data-label="Subtotal">
    <div id="subtotal_<%= product.id %>">
      <%= render "carts/subtotal", product: product %>
    </div>
  </td>
</tr>

app/views/carts/_order_summary.html.erb
<li class="single-product d-flex justify-content-start">
                                <div class="product-img">
                                    <%= image_tag product.image_url ? product.image_url : '' %>
                                </div>
                                <div class="product-info">
                                    <h5 class="product-title"><a href="#"><%= product.name %></a></h5>
                                    <div class="product-total d-flex align-items-center">
                                        <div class="quantity">
                                            <div class="quantity d-flex align-items-center">
                                                <div class="quantity-nav nice-number d-flex align-items-center">
                                                    <%= current_user.carts.active.where(product_id: product.id).count %>
                                                </div>
                                            </div>
                                        </div>
                                        <strong> <i class="bi bi-x-lg px-2"></i>
                                            <span class="product-price"><%= product.price %> VND</span>
                                        </strong>
                                    </div>
                                </div>
                            </li>

app/views/carts/_subtotal.html.erb
<div id="<%= dom_id product %>">
  <%= product.price * current_user.carts.active.where(product_id: product.id).count %>
</div>

app/views/carts/_total.html.erb
<div id="<%= dom_id current_user %>">
  <%= total %>
</div>

app/views/carts/checkout.html.erb
<div class="checkout-section pt-120 pb-120">
        <div class="container">
            <div class="row g-4">
                <div class="col-lg-7">
                    <div class="form-wrap box--shadow mb-30">
                        <h4 class="title-25 mb-20">Billing Details</h4>
                        <%= form_with(url: checkout_momo_carts_path, multipart: true, local: true) do |f| %>
                        
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-inner">
                                        <label>First Name</label>
                                        <input type="text" name="first_name" placeholder="Your first name" value="<%= current_user.first_name %>">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-inner">
                                        <label>Last Name</label>
                                        <input type="text" name="last_name" placeholder="Your last name" value="<%= current_user.last_name %>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-inner">
                                        <label>Address</label>
                                        <input type="text" name="address" placeholder="Your address" value="<%= current_user.address %>" required>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-inner">
                                        <label>Phone Number</label>
                                        <input type="text" name="phone_number" placeholder="Your Phone Number" value="<%= current_user.phone_number %>" required>
                                    </div>
                                </div>
                                 <div class="place-order-btn">
                                    <button type="submit" class="primary-btn1 lg-btn">Pay with momo</button>
                                    <%= link_to "Pay in cash", cash_carts_path, data: { turbo: true, turbo_method: :put}, class: "primary-btn2 btn-lg" %>
                                </div>
                            </div>
                        <% end %>
                        
                    </div>
                </div>
                <aside class="col-lg-5">
                    <div class="added-product-summary mb-30">
                        <h5 class="title-25 checkout-title">
                            Order Summary
                        </h5>
                        <ul class="added-products">
                            <% @products.each do |product| %>
                                <%= render partial: "carts/order_summary", locals: {product: product} %>
                            <% end %>
                        </ul>
                    </div>
                    <div class="summery-card total-cost mb-30">
                        <table class="table cost-summery-table total-cost">
                            <thead>
                                <tr>
                                    <th>Total</th>
                                    <th><%= @total %></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </aside>
            </div>
        </div>
    </div>

app/views/carts/create.turbo_stream.erb
<%= turbo_stream.prepend "cart_#{current_user.id}" do %>
  <%= render "layouts/cart", cart: @cart %>
<% end %>

app/views/carts/index.html.erb
<div class="cart-section pt-120 pb-120">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="table-wrapper">
          <table class="eg-table table cart-table">
            <thead>
            <tr>
              <th>Delete</th>
              <th>Image</th>
              <th>Product Name</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Subtotal</th>
            </tr>
            </thead>
            <tbody>
            <% @carts.each do |product| %>
            <%= render partial: "carts/cart", locals: {product: product} %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row g-4">
      <div class="col-lg-4">
      </div>
      <div class="col-lg-8">
        <table class="table total-table">
          <thead>
          <tr>
            <th>Cart Totals</th>
            <th id="total_<%= current_user.id %>">
              <%= render partial: "carts/total", locals: {total: @total} %>
            </th>
          </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
        <ul class="cart-btn-group">
          <li><a href="<%= shop_path %>" class="primary-btn2 btn-lg">Continue to shopping</a></li>
          <% if current_user.carts.active.count > 0 %>
            <li>
              <%= link_to "Checkout", checkout_carts_path, class: "primary-btn3 btn-lg" %>
              <%
=begin%>
 <%= button_to checkout_momo_carts_path, data: { turbo: false }, class: "primary-btn3 btn-lg" do %>
                Checkout with momo
              <% end %> 
<%
=end%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/carts/update_quantity.turbo_stream.erb
<%= turbo_stream.prepend "subtotal_#{@product.id}" do %>
  <%= render "carts/subtotal", product: @product %>
<% end %>
<%= turbo_stream.prepend "total_#{current_user.id}" do %>
  <%= render "carts/total", total: @total %>
<% end %>
<%= turbo_stream.prepend "cart_#{current_user.id}" do %>
  <%= render "layouts/cart", cart: @cart %>
<% end %>