config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chat_messages
  resources :products
  resources :histories
  resources :bookings
  resources :manage_bookings
  resources :profile
  resources :bills, only: [:index, :show, :update]
  resources :users do
    collection do
      post :import
    end
  end
  get :update_password, to: "welcome#update_password", as: :update_password
  put :edit_password, to: "welcome#edit_password", as: :edit_password
  resources :rooms do
    collection do
      post :import
    end
  end
  resources :carts do
    collection do
      patch :update_quantity
      post :checkout_momo
      get :checkout
      put :cash
    end
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root "welcome#index"
  get "shop", to: "welcome#shop"
  get "shop_detail/:id", to: "welcome#shop_detail", as: :shop_detail
  get "spa", to: "welcome#spa", as: :spa
  namespace :api do
    namespace :v1 do
      resources :bills, only: [:create]
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, dependent: :destroy
  enum r_type: [:apartment, :vip, :penthouse]
  enum weight: [:less_than_5, :five_to_ten, :ten_to_fifteen, :fifteen_to_twenty, :greater_than_20]
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource
  def index
    @rooms = Room.all
  end
  def new
    @room = Room.new
  end

  def create
    room = Room.new room_params
    if room.save
      flash[:notice] = "Create room successfully!"
    else
      flash[:notice] = "Create room failed!"
    end
    redirect_to rooms_path
  end

  def import
    creek = Creek::Book.new(params[:file].tempfile.path, with_headers: true)
    sheet = creek.sheets[0]
    sheet.rows.each_with_index do |row, index|
      next if index == 0 # Skip the header row
      row_values = row.values
      
      room = Room.new(r_type: row_values.first.to_i, weight: row_values[1].to_i, price: row_values[2], quantity: row_values[3])
      if room.save
      else
        next
      end
    end

    redirect_to rooms_path, notice: 'Excel file imported successfully.'
  rescue StandardError => e
    redirect_to rooms_path, alert: "Error importing Excel file: #{e.message}"
  end

  def edit
    @room = Room.find_by id: params[:id]
  end

  def update
    @room = Room.find_by id: params[:id]
    if @room.update room_params
      flash[:notice] = "Update room successfully!"
    else
      flash[:notice] = "Update room failed!"
    end
    redirect_to rooms_path
  end

  def destroy
    Room.find_by(id: params[:id]).destroy
    flash[:notice] = "Delete room successfully."
    # redirect_to "#{request.referer}##{params[:id]}"
    respond_to do |format|
      format.js { render js: "window.location.href = '/rooms';" }
    end
  end

  private

  def room_params
    params.require(:room).permit :r_type, :weight, :price, :quantity
  end
end

app/views/rooms/_form.html.erb
<%= form_with(model: @room) do |form| %>
<div class="row">
  <div class="input-field col s12">
    <%= form.select :r_type, Room.r_types.keys.map{|type| [type.humanize, type]}
    %>
    <label for="r_type">Room type</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <%= form.select :weight, Room.weights.keys.map{|type| [weight_text(type), type]}
    %>
    <label for="weight">Weight</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <%= form.number_field :price, min: 1, required: true %>
    <label for="price">Price/Day</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <%= form.number_field :quantity, min: 1, required: true %>
    <label for="quantity">Quantity</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <button
      class="btn cyan waves-effect waves-light right"
      type="submit"
      name="action"
    >
      Submit
    </button>
  </div>
</div>
<% end %>

app/views/rooms/_room.html.erb
<tr id="<%= dom_id room %>">
  <td><%= room.r_type.humanize %></td>
  <td><%= weight_text(room.weight) %></td>
  <td><%= room.price %></td>
  <td><%= room.quantity %></td>
  <td>
    <%= link_to edit_room_path(room) do %>
    <i class="material-icons">edit</i><span class="hide-menu"></span>
    <% end %>
    <!--    <a href="#"><i class="material-icons">edit</i><span class="hide-menu"></span></a>-->
    <%= link_to room_path(room), data: { turbo: true, turbo_method: :delete,
    turbo_confirm: "Are you sure?" } do %>
    <i class="material-icons">delete</i><span class="hide-menu"></span>
    <% end %>
  </td>
</tr>

app/views/rooms/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <h5 class="card-title">Edit Room</h5>
          <%= render "form"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <h5 class="card-title">Room List</h5>
        <table class="responsive-table datatable-select-inputs">
          <thead>
          <tr>
            <th style="width: 15%">Type</th>
            <th style="width: 30%">Weight</th>
            <th style="width: 15%">Price</th>
            <th style="width: 15%">Quantity</th>
            <th style="width: 15%">Action</th>
          </tr>
          </thead>
          <tbody>
            <%= render @rooms %>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <h5 class="card-title">Add new Room</h5>
          <%= render "form"%>
        </div>
      </div>
    </div>
    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <h5 class="card-title">Or import file (excel)</h5>
          <%= form_with(url: import_rooms_path, local: true, multipart: true) do
          |form| %>
          <div class="row">
            <div class="input-field col s10">
              <div class="file-field input-field">
                <div class="btn cyan">
                  <span>File</span>
                  <%= form.file_field :file, accept: '.xlsx' %>
                </div>
                <div class="file-path-wrapper">
                  <input
                    class="file-path validate"
                    type="text"
                    placeholder="Choose File Here"
                  />
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <button
                    class="btn cyan waves-effect waves-light right"
                    type="submit"
                    name="action"
                  >
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>