config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chat_messages
  resources :products
  resources :histories
  resources :bookings
  resources :manage_bookings
  resources :profile
  resources :bills, only: [:index, :show, :update]
  resources :users do
    collection do
      post :import
    end
  end
  get :update_password, to: "welcome#update_password", as: :update_password
  put :edit_password, to: "welcome#edit_password", as: :edit_password
  resources :rooms do
    collection do
      post :import
    end
  end
  resources :carts do
    collection do
      patch :update_quantity
      post :checkout_momo
      get :checkout
      put :cash
    end
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root "welcome#index"
  get "shop", to: "welcome#shop"
  get "shop_detail/:id", to: "welcome#shop_detail", as: :shop_detail
  get "spa", to: "welcome#spa", as: :spa
  namespace :api do
    namespace :v1 do
      resources :bills, only: [:create]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :carts, dependent: :destroy
  has_many :bill_products, dependent: :destroy
  enum :category, [:dog, :cat, :bird, :small_animal, :fish]

  def image_url
    if self.image.attachment
      self.image.attachment.url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ActiveStorage::SetCurrent
  load_and_authorize_resource
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.js { render js: "window.location.href = '/products';" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :quantity, :image, :category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<style>
.imagePreview{
  background-size:     cover;                      /* <------ */
  background-repeat:   no-repeat;
  background-position: center center;
  margin-top: 30px;
  height: 200px;
}
</style>
      <div class="card" style="height: 650px">
        <div class="card-content">
          <%= form_with(model: product, class: "contents") do |form| %>
            <% if product.errors.any? %>
              <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
                <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                <ul>
                  <% product.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="row">
              <div class="col s12" style="margin-bottom: 20px">
                  <label>Name *</label>
                  <%= form.text_field :name, required: true %>
              </div>
              <div class="col s4" style="margin-bottom: 20px">
                  <label>Price *</label>
                  <%= form.number_field :price, min: 1, required: true %>
              </div>
              <div class="col s4" style="margin-bottom: 20px">
                  <label>Quantity *</label>
                  <%= form.number_field :quantity, min: 1, required: true %>
              </div>
              <div class="col s4" style="margin-bottom: 20px">
                  <label>Category *</label>
                  <%= form.select :category, Product.categories.keys.map{|type| [type.humanize, type]} %>
              </div>
              <div class="col s6 imageX">
                  <label class="col s12" style="margin-bottom: 20px">Image</label>
                  <%= form.file_field :image, class: "uploadFile", accept:'image/*' %>
                  <div class="imagePreview"></div>
              </div>
              <div class="col s6">
                <label>Description</label>
                <%= form.text_area :description, rows: 4, cols: 5, style: "height: 19rem" %>
              </div>
            </div>
            <br/>
            <button class="btn cyan waves-effect waves-light right" type="submit">Submit</button>
          <% end %>
        </div>
      </div>

<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
    jQuery(function($) {
        $(document).on("change",".uploadFile", function()
        {
            var uploadFile = $(this);
            var files = !!this.files ? this.files : [];
            if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
            console.log(/^image/.test( files[0].type))

            if (/^image/.test( files[0].type)){ // only image file
                var reader = new FileReader(); // instance of the FileReader
                reader.readAsDataURL(files[0]); // read the local file

                reader.onloadend = function(){ // set image data as background of div
                    //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                    uploadFile.closest(".imageX").find('.imagePreview').css("background-image", "url("+this.result+")");
                }
            }

        });
        $(document).ready( function()
        {
            // var uploadFile = $(this);
            // var files = !!this.files ? this.files : [];
            // if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
            console.log("<%= product.image_url ? product.image_url : '' %>")

            // if (/^image/.test( files[0].type)){ // only image file
            //     var reader = new FileReader(); // instance of the FileReader
            //     reader.readAsDataURL(files[0]); // read the local file

            //     reader.onloadend = function(){ // set image data as background of div
            //         //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                    document.getElementsByClassName('imagePreview')[0].style.backgroundImage = "url(<%= product.image_url ? product.image_url : '' %>)";
            //     }
            // }

        });
    });
</script>

app/views/products/_product.html.erb
<tr id="<%= dom_id product %>">
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.price %></td>
  <td><%= image_tag product.image_url ? product.image_url : '', style: "height: 100px; object-fit: contain" %></td>
  <td><%= product.quantity %></td>
  <td><%= product.category %></td>
  <td>
    <%= link_to edit_product_path(product) do %>
      <i class="material-icons">edit</i><span class="hide-menu"></span>
    <% end %>
    <%= link_to product_path(product), data: { turbo: true, turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <i class="material-icons">delete</i><span class="hide-menu"></span>
    <% end %>
  </td>
</tr>

app/views/products/edit.html.erb
<div class="container" style="margin-bottom: 30px; margin-top: 30px">
  <div class="row justify-content-center">
    <div class="form-wrapper wow fadeInUp" data-wow-duration="1.5s" data-wow-delay=".2s" style="width: 100%">
      <div class="form-title">
        <h3>Edit Product</h3>
      </div>
      <%= render "form", product: @product %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <h5 class="card-title">Products List</h5>
        <table class="responsive-table datatable-select-inputs">
          <thead>
          <tr>
            <th style="width: 15%">Name</th>
            <th style="width: 25%">Description</th>
            <th style="width: 15%">Price</th>
            <th style="width: 20%">Image</th>
            <th style="width: 10%">Quantity</th>
            <th style="width: 10%">Category</th>
            <th style="width: 5%">Action</th>
          </tr>
          </thead>
          <tbody>
          <%= render @products %>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container" style="margin-bottom: 30px; margin-top: 30px">
  <div class="row justify-content-center">
    <div class="form-wrapper wow fadeInUp" data-wow-duration="1.5s" data-wow-delay=".2s" style="width: 100%">
      <div class="form-title">
        <h3>New Product</h3>
      </div>
      <%= render "form", product: @product %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to 'Edit this product', edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this product', product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>